sudo: required
services:
  - docker

branches:
  only:
  - master

script:
  - ./bin/build-project.sh -g

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/$DOCKER_IMAGE;
    fi
